Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
