Metrics/LineLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/EmptyLinesAroundAccessModifier:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Lint/UselessAccessModifier:
  Enabled: false

Lint/ShadowedException:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/WordArray:
  Enabled: false
