##
# exception.rb
# Created July, 2018
# By Ron Bowes
#
# See LICENSE.md
#
# Custom exception for DNS tunnel driver. Lets us determine when an error is
# generated by us, as opposed to a library.
##

module Dnscat2
  module TunnelDrivers
    module DNS
      class Exception < ::StandardError
      end
    end
  end
end
